using APP.Framework.Domain;

using System;

using System.Diagnostics;

/*Generated by .NET Class Generator Tools*/

namespace Patuh.Domain
{
    [DebuggerStepThrough()]
    public partial class TrImageAttachment : AbstractTable
    {
        #region Data Member
        private long _id;
        private long _headerid;
        private byte[] _image;
        private int _sequence;
        private string _ccreated;
        private DateTime _dcreated;
        private string _clastupdated;
        private DateTime _dlastupdated;
        #endregion

        #region Default Value
        public TrImageAttachment()
        {
        }
        #endregion


        #region Properties
        public long Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
                Modify();
            }
        }

        public long HeaderId
        {
            get
            {
                return _headerid;
            }
            set
            {
                _headerid = value;
                Modify();
            }
        }

        public byte[] Image
        {
            get
            {
                return _image;
            }
            set
            {
                _image = value;
                Modify();
            }
        }

        public int Sequence
        {
            get
            {
                return _sequence;
            }
            set
            {
                _sequence = value;
                Modify();
            }
        }


        public string cCreated
        {
            get
            {
                return _ccreated;
            }
            set
            {
                _ccreated = value;
                Modify();
            }
        }

        public DateTime dCreated
        {
            get
            {
                return _dcreated;
            }
            set
            {
                _dcreated = value;
                Modify();
            }
        }

        public string cLastUpdated
        {
            get
            {
                return _clastupdated;
            }
            set
            {
                _clastupdated = value;
                Modify();
            }
        }

        public DateTime dLastUpdated
        {
            get
            {
                return _dlastupdated;
            }
            set
            {
                _dlastupdated = value;
                Modify();
            }
        }

        

        #endregion

    }
}