USE [master]
GO

/****** Object:  Database [Patuh]    Script Date: 6/19/2018 8:07:15 PM ******/
CREATE DATABASE [Patuh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestingFrameWork', FILENAME = N'D:\Database\TestingFrameWork.mdf' , SIZE = 17408KB , MAXSIZE = 153600KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestingFrameWork_log', FILENAME = N'D:\Database\TestingFrameWork_log.ldf' , SIZE = 123648KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Patuh] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Patuh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Patuh] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Patuh] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Patuh] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Patuh] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Patuh] SET ARITHABORT OFF 
GO

ALTER DATABASE [Patuh] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Patuh] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Patuh] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Patuh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Patuh] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Patuh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Patuh] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Patuh] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Patuh] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Patuh] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Patuh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Patuh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Patuh] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Patuh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Patuh] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Patuh] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Patuh] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Patuh] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Patuh] SET  MULTI_USER 
GO

ALTER DATABASE [Patuh] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Patuh] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Patuh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Patuh] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Patuh] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Patuh] SET  READ_WRITE 
GO

